Remove `#[derive(Debug)]` from library structs
google/tarpc pull request #327
Opened 2020-10-30 10:48 UTC by chansuke

Fixes #326.

2020-11-03 00:17 UTC, tikue requested changes

2020-11-03 00:17 UTC, tikue commented on tarpc/src/rpc.rs
> -#![deny(missing_docs, missing_debug_implementations)]
Let's leave this in

2020-11-03 00:17 UTC, tikue commented on tarpc/src/rpc/server.rs
> +        write!(f, "NewClient {:?}", self)
```suggestion
        write!(f, "BaseChannel")
```

2020-11-04 09:36 UTC, chansuke commented on tarpc/src/rpc.rs
> -#![deny(missing_docs, missing_debug_implementations)]
Ok!

2020-11-04 09:43 UTC, chansuke commented
@tikue Thank you for the review.

2020-11-04 19:24 UTC, merged

2020-11-04 19:25 UTC, tikue commented
Woo! Thank you!