Feature/tls over tcp example
google/tarpc pull request #398
Opened 2023-03-12 20:15 UTC by cguentherTUChemnitz

i implemented a working example for tls_over_tpc, based on top of tarpc/examples/custom_transport and tokio-rustls examples and tests. Certificates are picked from tokio-rustls tests.

2023-03-17 09:39 UTC, tikue requested changes
Thanks so much for contributing this example, this is awesome! I admit it mostly just looks like mumbo jumbo to me :) but the dependencies all look legit, and it's just an example, so I don't have any concerns.

I just have 2 tiny nits, take a look and then I think we can get this merged!

2023-03-17 09:59 UTC, cguentherTUChemnitz commented
I will update in the next week this PR. I have locally fiddled around also with client-auth and i was able to get it working correctly based on certs generating the same way as rustls is doing it for their tests:
https://github.com/rustls/rustls/tree/main/test-ca

2023-03-17 10:40 UTC, cguentherTUChemnitz commented on tarpc/examples/tls_over_tcp.rs
> +        .drain(..)
I don't know. This was copied from rustls example. I migrated now to into_iter. Seems to work fine for me ;)

2023-03-17 10:41 UTC, cguentherTUChemnitz commented on tarpc/examples/tls_over_tcp.rs
> +    let mut keys = keys.drain(..).map(rustls::PrivateKey);
I added a more generalized private key loading function encapsulating this.

2023-03-21 23:38 UTC, tikue approved these changes
Looks good, thanks so much!

2023-03-21 23:44 UTC, tikue commented on tarpc/examples/certs/eddsa/end.chain
Where does this come from? It looks different from what's in https://github.com/tokio-rs/tls/blob/master/tokio-rustls/tests/end.chain — likewise for the other cert/chain/key files

2023-03-21 23:44 UTC, tikue requested changes
Actually, I'd just like to understand a bit better how you generated the certificate files. Thanks so much!

2023-03-22 16:28 UTC, cguentherTUChemnitz commented on tarpc/examples/certs/eddsa/end.chain
Good point. I have used the test-ca creation script from rustls, which generates a ca, as well as client and server certs. Since they are already also configured for client out i migrated to those ones. I linked the "how to create the certs" in the following comment line:
https://github.com/google/tarpc/pull/398/files#diff-ab7dfcbf41b879bf0b90f96552153640d5f8d9268cde12f3c20faa97cb97f6c7R33

2023-03-22 17:20 UTC, tikue commented on tarpc/examples/certs/eddsa/end.chain
Got it, thanks!

2023-03-22 17:35 UTC, merged

2023-04-01 18:13 UTC, IzumiRaine commented
Thank you so much, this is exactly what I needed right now :)

A minor comment on creating the client's root store: <https://github.com/google/tarpc/blob/bed85e282710a5d21444fd25a5c0f55796ffc889/tarpc/examples/tls_over_tcp.rs#L115-L122>
You can instead use `root_store.add` like when setting up the server's roots (it calls `RootCertStore::add_server_trust_anchors` internally), which is a bit simpler.

2023-04-01 18:40 UTC, tikue commented
Thanks @IzumiRaine ! A PR with the fix would be most welcome ☺️

2023-04-01 19:32 UTC, IzumiRaine commented
Oh, sure! I'll send a PR once I had a chance to play with it some more.