update syn 2.0
google/tarpc pull request #427
Opened 2024-02-03 13:33 UTC by getong

2024-02-03 21:45 UTC, tikue commented on plugins/src/lib.rs
> +            if let Expr::Lit(expr_lit) = &meta.value {
what if meta.value does not match Expr::Lit? I think there should be an error in that case.

On HEAD, the following service won't compile, but it does with this change:

```rs
#[tarpc::service(derive_serde = loop {})]
pub trait World {
    /// Returns a greeting for name.
    async fn hello(name: String) -> String;
}
```

Error on HEAD:

```
error: expected literal
  --> example-service/src/lib.rs:12:33
   |
12 | #[tarpc::service(derive_serde = loop {})]
```

Also, I think this means we're missing a test case. Would you like to add one to tarpc/tests/compile_fail? I'm also happy to add it too.

2024-02-03 21:46 UTC, tikue commented
Thanks very much! Left one review comment regarding literal validation in `derive_serde`

2024-02-03 22:03 UTC, tikue commented on plugins/src/lib.rs
> +                    Lit::Bool(LitBool { value: false, .. }) => result = result.and(Ok(Some(false))),
Here's a refactoring that catches the non-literal error:

```suggestion
            let Expr::Lit(expr_lit) = &meta.value else {
                extend_errors!(
                    result,
                    syn::Error::new(
                        meta.value.span(),
                        "`derive_serde` expects a literal of type `bool`"
                    )
                );
                continue;
            };
            match expr_lit.lit {
                Lit::Bool(LitBool { value: true, .. }) if cfg!(feature = "serde1") => {
                    result = result.and(Ok(Some(true)))
                }
                Lit::Bool(LitBool { value: true, .. }) => {
                    extend_errors!(
                        result,
                        syn::Error::new(
                            meta.span(),
                            "To enable serde, first enable the `serde1` feature of tarpc"
                        )
                    );
                }
                Lit::Bool(LitBool { value: false, .. }) => result = result.and(Ok(Some(false))),
```

2024-02-03 22:14 UTC, tikue commented on plugins/src/lib.rs
> +            if let Expr::Lit(expr_lit) = &meta.value {
Disregard that last question — I added a test case for this in https://github.com/google/tarpc/commit/cef01a1d590923a4577292d49c7a880ac5e17eb1 (feel free to TRYBUILD=overwrite if you update the compile error to be more specific)

2024-02-04 00:46 UTC, getong commented
clap, tokio-serde, console-subscriber, all of them upgrade to new version, since they use syn 1.0, which cause the ci error.
After upgrading new version, the ci is ok now.

2024-02-04 03:52 UTC, tikue commented on tarpc/Cargo.toml
> +tokio-serde = { optional = true, git = "https://github.com/tamird/tokio-serde", branch = "remove-educe", features = ["json", "bincode"] }
I'd rather depend on tokio-serde even if it pulls in 2 versions of syv. Consider a PR to tokio-serde?

2024-02-04 04:11 UTC, tikue requested changes
Looks good other than the tokio-serde change

2024-02-04 07:35 UTC, getong commented
https://github.com/carllerche/tokio-serde/pull/31

I found this pr， but it does not be merged.

2024-02-04 10:01 UTC, getong commented
@tikue 
Everything is ok now

2024-02-04 20:58 UTC, tikue approved these changes

2024-02-04 20:59 UTC, tikue commented
Thank you!

2024-02-04 21:01 UTC, merged